# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-09 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthqquser',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='oauthqquser',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
